In [ ]:
!pip install np_utils

In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf
import matplotlib.pyplot as plt
from tensorflow.keras import layers
from tensorflow import keras
import tensorflow_addons as tfa
import tensorflow

# Loading the Data

In [ ]:
x_train  = np.load("/content/drive/MyDrive/Ghanapriya Ma'am/WESAD/x_train.npy")
x_test = np.load("/content/drive/MyDrive/Ghanapriya Ma'am/WESAD/x_test.npy")
y_train = np.load("/content/drive/MyDrive/Ghanapriya Ma'am/WESAD/y_train.npy")
y_test  = np.load("/content/drive/MyDrive/Ghanapriya Ma'am/WESAD/y_test.npy")
x_whole = np.concatenate((x_train , x_test),axis = 0 )
np.save("/content/drive/MyDrive/Ghanapriya Ma'am/WESAD/x_whole.npy", x_whole)
print(x_whole.shape)
y_whole  = np.concatenate((y_train , y_test), axis = 0)
np.save("/content/drive/MyDrive/Ghanapriya Ma'am/WESAD/y_whole.npy", y_whole)
print(y_whole.shape)

In [ ]:
x = np.load("/content/drive/MyDrive/Ghanapriya Ma'am/WESAD/x_whole.npy")
print(x.shape)
y = np.load("/content/drive/MyDrive/Ghanapriya Ma'am/WESAD/y_whole.npy")
y = pd.DataFrame(y)
print(y.shape)

(16492, 5, 3500, 1)
(16492, 1)


In [ ]:
print("Before Replacing the labels:\n",pd.DataFrame(y).value_counts())
y_new = y.replace([1,2,3], [0,1,2])
print("After Repalacing the labels:\n", y_new.value_counts())

Before Replacing the labels:
 1    8777
2    4957
3    2758
dtype: int64
After Repalacing the labels:
 0    8777
1    4957
2    2758
dtype: int64


In [ ]:
from sklearn.model_selection import train_test_split
features_train, features_test, target_train, target_test = train_test_split( x, y_new, test_size=0.1, random_state=10)
print(features_train.shape)
print(target_train.shape)
print(features_test.shape)
print(target_test.shape)
print()
print(pd.DataFrame(target_train).value_counts())
print(target_train[0:5])
print()
print(pd.DataFrame(target_test).value_counts())
print(target_test[0:5])

(14842, 5, 3500, 1)
(14842, 1)
(1650, 5, 3500, 1)
(1650, 1)

0    7886
1    4467
2    2489
dtype: int64
       0
15809  0
6569   2
5867   0
14124  1
6414   0

0    891
1    490
2    269
dtype: int64
       0
9160   1
13569  1
14035  1
7888   0
6780   1


In [ ]:
# Training set class ratio for weight:
pd.DataFrame(target_train).value_counts()

0    7886
1    4467
2    2489
dtype: int64

In [ ]:
target_trainoe = tensorflow.keras.utils.to_categorical(target_train)
print(target_trainoe[0:5])
print()
target_testoe = tensorflow.keras.utils.to_categorical(target_test)
print(target_testoe[0:5])

[[1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]]

[[0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]]


In [ ]:
print(target_trainoe.shape)
print(target_testoe.shape)

(14842, 3)
(1650, 3)


In [ ]:

np.save("/content/drive/MyDrive/Ghanapriya Ma'am/WESAD/final_train_test_set/features_train.npy" , features_train)
np.save("/content/drive/MyDrive/Ghanapriya Ma'am/WESAD/final_train_test_set/target_trainoe.npy" , target_trainoe)
np.save("/content/drive/MyDrive/Ghanapriya Ma'am/WESAD/final_train_test_set/features_test.npy" , features_test)
np.save("/content/drive/MyDrive/Ghanapriya Ma'am/WESAD/final_train_test_set/target_testoe.npy" , target_testoe)
